import { IProduct } from "@/entities/product";

export const BEST_SELLING_PRODUCTS: IProduct[] = [
  {
    id: 1,
    title: "Sakarias Armchair",
    category: "Chair",
    price: 392,
    image: "/assets/chair-1.png",
    rating: 5,
  },
  {
    id: 2,
    title: "Baltsar Chair",
    category: "Chair",
    price: 299,
    image: "/assets/chair-2.png",
    rating: 4.7,
  },
  {
    id: 3,
    title: "Anjay Chair",
    category: "Chair",
    price: 519,
    image: "/assets/chair-3.png",
    rating: 5,
  },
  {
    id: 4,
    title: "Nyantuy Chair",
    category: "Chair",
    price: 921,
    image: "/assets/chair-4.png",
    rating: 5,
  },
  {
    id: 5,
    title: "Nordic Dream Bed",
    category: "Beds",
    price: 1250,
    image: "/assets/bed-1.png",
    rating: 5,
  },
  {
    id: 6,
    title: "Silence Platform Bed",
    category: "Beds",
    price: 890,
    image: "/assets/bed-2.png",
    rating: 5,
  },
  {
    id: 7,
    title: "Cloud Nine Upholstered",
    category: "Beds",
    price: 1420,
    image: "/assets/bed-3.png",
    rating: 5,
  },
  {
    id: 8,
    title: "Kingston Oak Frame",
    category: "Beds",
    price: 1100,
    image: "/assets/bed-4.png",
    rating: 5,
  },
  {
    id: 9,
    title: "Serene Sectional Sofa",
    category: "Sofa",
    price: 1560,
    image: "/assets/sofa-1.png",
    rating: 5,
  },
  {
    id: 10,
    title: "Velvet Lounge Settee",
    category: "Sofa",
    price: 980,
    image: "/assets/sofa-2.png",
    rating: 4,
  },
  {
    id: 11,
    title: "Urban Comfort 3-Seater",
    category: "Sofa",
    price: 1200,
    image: "/assets/sofa-3.png",
    rating: 4.8,
  },
  {
    id: 12,
    title: "Minimalist Loft Sofa",
    category: "Sofa",
    price: 1350,
    image: "/assets/sofa-4.png",
    rating: 4,
  },
  {
    id: 13,
    title: "Glow Sphere Table Lamp",
    category: "Lamp",
    price: 145,
    image: "/assets/lamp-1.png",
    rating: 5,
  },
  {
    id: 14,
    title: "Onyx Arc Floor Lamp",
    category: "Lamp",
    price: 210,
    image: "/assets/lamp-2.png",
    rating: 5,
  },
  {
    id: 15,
    title: "Pixel Task Desk Lamp",
    category: "Lamp",
    price: 85,
    image: "/assets/lamp-3.png",
    rating: 4,
  },
  {
    id: 16,
    title: "Lumina Timber Nightlamp",
    category: "Lamp",
    price: 120,
    image: "/assets/lamp-4.png",
    rating: 3.5,
  },
];